server:
    port: 8080
spring:
    application:
        name: @artifactId@
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.92.150:8848
                username: nacos
                password: nacos

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.92.150:3306/lly_svr?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&&useSSL=false
        username: root
        password: 123456
    redis:
        host: 192.168.92.150
        port: 6379
        password: 123456
        database: 6
        jedis:
          pool:
              max-active: 8
logging:
    level:
        root: debug
mybatis:
    mapper-locations: classpath:mapper/*.xml
    #??????
    configuration:
        map-underscore-to-camel-case: false
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    app:
        workId: 1
        workerIdBits: 10